interface Env {
  API_WORKER: Fetcher;
  EMAIL_WORKER_INTERNAL_TOKEN: string;
  EMAIL_WORKER_RATE_LIMITER?: RateLimit;
  RECEIPT_DEDUPE: KVNamespace;
  RECEIPT_DEDUPE_TTL_SECONDS?: string;
  RECEIPT_RETRY_TTL_SECONDS?: string;
  RECEIPT_TO_ADDRESS?: string;
}
